apiVersion: v1
kind: ServiceAccount
metadata:
  name: metrics-server
  namespace: kube-system
---
# Note: For your portfolio, explain that 'kube-system' is the 
# standard namespace for cluster-wide utilities.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-server
  namespace: kube-system
spec:
  selector:
    matchLabels:
      k8s-app: metrics-server
  template:
    metadata:
      labels:
        k8s-app: metrics-server
    spec:
      containers:
      - name: metrics-server
        image: registry.k8s.io/metrics-server/metrics-server:v0.6.3
        args:
        - --kubelet-insecure-tls # Required for homelabs/self-signed certs
        - --kubelet-preferred-address-types=InternalIP
        ports:
        - containerPort: 4443
          name: https
          protocol: TCP
