apiVersion: v1
kind: ConfigMap
metadata:
  name: travel-goals-html
data:
  index.html: |
    <html>
    <body style="background-color: #2c3e50; color: white; font-family: sans-serif; text-align: center; padding-top: 50px;">
      <h1>DBITK Platform Lab: Online</h1>
      <hr style="width: 50%;">
      <h2>Adventure Goals:</h2>
      <ul style="list-style-position: inside;">
        <li>Travel the world with her</li>
        <li>Pay off student loans</li>
        <li>Hit that competitive salary</li>
      </ul>
      <p style="margin-top: 20px;"><i>Status: Automatically deployed via GitOps</i></p>
    </body>
    </html>
