apiVersion: apps/v1
kind: Deployment
metadata:
  name: scalable-web-platform
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      labels:
        app: web-server
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html # This is where Nginx looks for files
      volumes:
      - name: html-volume
        configMap:
          name: travel-goals-html
